name: webapp-stack

networks:
  supabase_default:
    external: true

volumes:
  nginx_logs:
  app_logs:

services:
  # Frontend Application (Lead Persona Dashboard - Vite React)
  webapp:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=http://217.154.211.42:8000
        - VITE_SUPABASE_ANON_KEY=${ANON_KEY}
    container_name: lead-dashboard
    restart: unless-stopped
    environment:
      - VITE_SUPABASE_URL=http://217.154.211.42:8000
      - VITE_SUPABASE_ANON_KEY=${ANON_KEY}
      - VITE_APP_ENV=production
    networks:
      - supabase_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - app_logs:/var/log/nginx

  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    container_name: webapp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - supabase_default
    depends_on:
      - webapp
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Health Check Service
  healthcheck:
    image: alpine:latest
    container_name: webapp-healthcheck
    restart: "no"
    command: |
      sh -c '
        apk add --no-cache curl &&
        while true; do
          echo "Health check at $$(date)"
          curl -f http://nginx/health || echo "Nginx health check failed"
          curl -f http://webapp:3000/health || echo "WebApp health check failed"  
          curl -f http://supabase-kong:8000/health || echo "Supabase health check failed"
          sleep 60
        done
      '
    networks:
      - supabase_default
    depends_on:
      - nginx
      - webapp